<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.cigna</groupId>
    <artifactId>cigna-proyect</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>
    <name>CignaProyect</name>
    <description>Proyecto de microservicios Cigna</description>

    <modules>
        <module>discovery-server/discovery-server</module>
        <module>api-gateway/api-gateway</module>
        <module>usuario-service/usuario-service</module>
        <module>servicio-service/servicio-service</module>
        <module>tratamiento-service</module>
        <module>agenda-service/agenda-service</module>
        <module>reserva-service/reserva-service</module>
    </modules>

</project>
