spring:
  application:
    name: discovery-server
    # configuracion de eureka explicacion paso a paso
server:
  port: 8761  # puerto donde se ejecuta el servidor de descubrimiento
eureka:
  client:
    register-with-eureka: false # el servidor de descubrimiento no se registra a sí mismo
    fetch-registry: false # el servidor de descubrimiento no necesita obtener el registro de otros servicios
  instance:
    hostname: localhost # nombre de host del servidor de descubrimiento
    

